### PR TITLE
Fix karma cooldown bug

### PR DESCRIPTION
**Pull request by RuthRainbow**
Fix karma cooldown bug, refactor a little to add tests.
Return early on cooldown error to reduce indentation.

### CODE REVIEW

**Comment by RuthRainbow** [comment]
Formatting errors!

**Comment by RuthRainbow** [comment]
Re-open, GitHub picked up the formatting commit.

**Review by Jlobblet — APPROVED** [review]
Looks good to me

**Comment by Jlobblet** [comment]
Added all of #39 to this to resolve the merge conflict.

The original commits were b3da1c3, cb678b7, and d7d9f60.

**Pull request merged**
